ERROR_SUCCESS = 0
ERROR_NETWORK = -1
ERROR_UNIKEY_OR_PW = -2
ERROR_POST_PARAMS = -3
ERROR_SESSION_EXPIRED = -4
ERROR_OBJ_NOTFOUND = -5
ERROR_SERVER = -6

FUNC_NOTICE = 0
FUNC_RESULT = 1
FUNC_DETAILS= 2
